const templates = [
  {
    image: 'slider1.jpg',
    name: 'Collect emails (Form at bottom)',
    description: 'Collect user emails with the input form at the bottom',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    theme: 'purple',
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffffff',
      'textColor': '#333333',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#a153e0',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#dddddd',
      'borderWidth': 1,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider2.jpg',
    name: 'Collect emails (Form at left)',
    description: 'Collect user emails with the input form on the left of the body',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    theme: 'purple',
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffffff',
      'textColor': '#333333',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#a153e0',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#dddddd',
      'borderWidth': 1,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'left',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider4.jpg',
    name: 'Collect emails (Inline Form)',
    description: 'Collect user emails using an inline form',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    theme: 'purple',
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffffff',
      'textColor': '#333333',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#a153e0',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#dddddd',
      'borderWidth': 1,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'inline',
      'formOrientation': 'bottom',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar1.jpg',
    name: 'Top info bar',
    description: 'An info bar at the top of the page',
    tags: ['bar'],
    theme: 'white',
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffffff',
      'textColor': '#333333',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#a153e0',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#dddddd',
      'borderWidth': 1,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 1,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider5.jpg',
    name: 'Collect emails (Orange)',
    description: 'Collect user emails with an orange theme',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    theme: 'orange',
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffaf40',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#444444',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#ffffff',
      'inputBgColor': '#f3f3f3',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider6.jpg',
    name: 'Collect emails (Orange)',
    description: 'Collect user emails with an orange theme',
    theme: 'orange',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'name': '',
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffaf40',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#444444',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#ffffff',
      'inputBgColor': '#f3f3f3',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider7.jpg',
    name: 'Collect emails (Green)',
    description: 'Collect user emails with an green theme',
    theme: 'green',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'slider',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'name': '',
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider8.jpg',
    name: 'Collect emails (Green)',
    description: 'Collect user emails with an green theme',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    theme: 'green',
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style="text-align: right;">Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style="text-align: right;">Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'name': '',
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar2.jpg',
    name: 'Collect emails (Green)',
    description: 'Collect user emails with an green theme',
    theme: 'green',
    tags: ['bar'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'name': '',
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider9.jpg',
    name: 'Collect emails (Green)',
    theme: 'green',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'slider',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style=\'text-align: left;\'>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style=\'text-align: left;\'>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#6aa84f',
      'borderWidth': 10,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'top',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider10.jpg',
    name: 'Collect emails (Green)',
    theme: 'green',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style=\'text-align: left;\'>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style=\'text-align: left;\'>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#6aa84f',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'top',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider11.jpg',
    name: 'Collect emails (Orange)',
    theme: 'orange',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffaf40',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#444444',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#f0a43b',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#ffffff',
      'inputBgColor': '#f3f3f3',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image8.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'top',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider12.jpg',
    name: '',
    theme: 'green',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#93c925',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#777778',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fbfbfc',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image9.png',
      'imagePosition': 'right',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider13.jpg',
    name: '',
    theme: 'purple',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#ffffff',
      'textColor': '#333333',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#a153e0',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#a153e0',
      'borderWidth': 6,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'top',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar3.jpg',
    name: '',
    theme: 'purple',
    description: '',
    tags: ['bar'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': 'Signup to our newsletter',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#a153e0',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#713c9b',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': 'Signup to our newsletter to receive special offers and discounts direct to your inbox',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#dddddd',
      'borderWidth': 1,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#ededed',
      'inputBgColor': '#ffffff',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 1,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '',
      'imagePosition': 'none',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider14.jpg',
    name: '',
    theme: 'blue',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style=\'text-align: center;\'>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#247ba0',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#206989',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style=\'text-align: center;\'>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image9.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider15.jpg',
    name: '',
    theme: 'blue',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style=\'text-align: center;\'>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#247ba0',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#206989',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style=\'text-align: center;\'>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image9.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar4.jpg',
    name: '',
    theme: 'blue',
    description: '',
    tags: ['bar'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#247ba0',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#206989',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image9.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider16.png',
    name: '',
    theme: 'orange-red',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style="text-align: center;">Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#f66d3c',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#f66d3c',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style="text-align: center;">Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider17.png',
    name: '',
    theme: 'orange-red',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style="text-align: center;">Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#f66d3c',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#f66d3c',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style="text-align: center;">Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar5.png',
    name: '',
    theme: 'orange-red',
    description: '',
    tags: ['bar'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#f66d3c',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#444455',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider18.jpg',
    name: '',
    theme: 'red',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style="text-align: center;">Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#dd4242',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#dd4242',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style="text-align: center;">Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'right',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'slider19.jpg',
    name: '',
    theme: 'red',
    description: '',
    tags: ['modal', 'slider', 'before-post', 'after-post', 'inline', 'widget'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'modal',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p style="text-align: center;">Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#dd4242',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#dd4242',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p style="text-align: center;">Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  },
  {
    image: 'bar6.jpg',
    name: '',
    theme: 'red',
    description: '',
    tags: ['bar'],
    promo: {
      'id': null,
      'isEnabled': true,
      'goal': 'email',
      'promoType': 'bar',
      'placement': 'top',
      'pushPage': true,
      'headline': '<p>Signup to our newsletter</p>',
      'button': 'SIGNUP',
      'displayDelaySeconds': 5,
      'wiggleButton': true,
      'bgColor': '#dd4242',
      'textColor': '#ffffff',
      'textFont': 'Open Sans',
      'buttonColor': '#fff',
      'buttonBgColor': '#901111',
      'buttonFont': 'Open Sans',
      'hideCookieDuration': 30,
      'successCookieDuration': 30,
      'positionFixed': true,
      'linkUrl': '/',
      'openLinkNewWindow': false,
      'emailPlaceholder': 'Email',
      'namePlaceholder': 'Name',
      'leadListId': 0,
      'thankYouMessage': 'Thank you!',
      'conditionPage': 'all',
      'conditionPageUrl': '/',
      'conditionDeviceDesktop': true,
      'conditionDeviceTablet': true,
      'conditionDeviceMobile': true,
      'body': '<p>Signup to our newsletter to receive special offers and discounts direct to your inbox</p>',
      'close': 'Close',
      'animate': true,
      'size': 'medium',
      'borderColor': '#eeeeee',
      'borderWidth': 0,
      'emailProvider': 'optinengine',
      'customFormBody': '',
      'nameFields': 'single',
      'emailProviderListId': '',
      'saveToOptinEngineLeads': false,
      'disableDoubleOptin': false,
      'firstNamePlaceholder': 'First name',
      'lastNamePlaceholder': 'Last name',
      'name': '',
      'formFieldOrientation': 'stacked',
      'formOrientation': 'bottom',
      'formBgColor': '#fffcff',
      'inputBgColor': '#ebebeb',
      'inputBorderColor': '#eee',
      'inputBorderWidth': 0,
      'inputTextClass': 'dark',
      'inputBorderRadius': 3,
      'imageUrl': '{FLEX_PLUGIN_URL}/images/image2.png',
      'imagePosition': 'above',
      'borderType': 'solid',
      'borderPosition': 'all',
      'thankYouBody': '',
      'closeButtonAction': 'close',
      'closeButtonUrl': '/',
      'closeButtonNewWindow': false
    }
  }
]

module.exports = templates.map((template) => {
  return Object.assign({}, template, {
  })
})
